"use client"

import * as React from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createAsset } from "@/services/asset.service"
import type { AssetCategory } from "@/types/asset"

type Props = {
  children: React.ReactNode
  categories: AssetCategory[]
  onRegistered: () => void
}

export function AssetRegistrationSheet({ children, categories, onRegistered }: Props) {
  const [open, setOpen] = React.useState(false)
  const [submitting, setSubmitting] = React.useState(false)
  const [categoryId, setCategoryId] = React.useState("")
  const [condition, setCondition] = React.useState("New")
  const [isBookable, setIsBookable] = React.useState(false)

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const form = new FormData(event.currentTarget)
    const name = String(form.get("name") || "").trim()
    if (!name || !categoryId) {
      toast.error("Asset name and category are required")
      return
    }

    setSubmitting(true)
    try {
      await createAsset({
        name,
        categoryId: Number(categoryId),
        serialNumber: String(form.get("serialNumber") || "") || undefined,
        acquisitionDate: String(form.get("acquisitionDate") || "") || undefined,
        acquisitionCost: form.get("acquisitionCost") ? Number(form.get("acquisitionCost")) : undefined,
        condition,
        location: String(form.get("location") || "") || undefined,
        isBookable,
      })
      toast.success("Asset registered")
      setOpen(false)
      onRegistered()
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not register asset")
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Sheet open={open} onOpenChange={setOpen}>
      <SheetTrigger>{children}</SheetTrigger>
      <SheetContent className="sm:max-w-xl w-full">
        <SheetHeader>
          <SheetTitle>Register new asset</SheetTitle>
          <SheetDescription>The asset tag is generated by AssetFlow after registration.</SheetDescription>
        </SheetHeader>
        <form onSubmit={submit} className="flex flex-1 flex-col gap-5 overflow-y-auto px-6 pb-6">
          <div className="grid gap-2">
            <Label htmlFor="asset-name">Asset name</Label>
            <Input id="asset-name" name="name" placeholder="Dell Latitude 7420" required />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label>Category</Label>
              <Select value={categoryId} onValueChange={setCategoryId}>
                <SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger>
                <SelectContent>
                  {categories.map((category) => <SelectItem key={category.categoryId} value={String(category.categoryId)}>{category.name}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="asset-serial">Serial number</Label>
              <Input id="asset-serial" name="serialNumber" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="asset-date">Acquisition date</Label>
              <Input id="asset-date" name="acquisitionDate" type="date" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="asset-cost">Cost</Label>
              <Input id="asset-cost" name="acquisitionCost" type="number" min="0" step="0.01" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label>Condition</Label>
              <Select value={condition} onValueChange={setCondition}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>{["New", "Good", "Fair", "Poor", "Damaged"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="asset-location">Location</Label>
              <Input id="asset-location" name="location" placeholder="Main warehouse" />
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Switch id="asset-bookable" checked={isBookable} onCheckedChange={setIsBookable} />
            <Label htmlFor="asset-bookable">Make this a shared, bookable resource</Label>
          </div>
          <SheetFooter className="mt-auto px-0">
            <Button type="submit" disabled={submitting}>{submitting ? "Registering…" : "Register asset"}</Button>
          </SheetFooter>
        </form>
      </SheetContent>
    </Sheet>
  )
}
